document.write( '<!DOCTYPE html>\n' );
document.write( '<html>\n' );
document.write( '<head>   \n' );
document.write( '<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\" crossorigin=\"anonymous\">\n' );
document.write( '\n' );
document.write( '<style>\n' );
document.write( '.mytext{\n' );
document.write( '    border:0;padding:10px;background:white;\n' );
document.write( '}\n' );
document.write( '.text{\n' );
document.write( '    width:75%;display:flex;flex-direction:column;\n' );
document.write( '}\n' );
document.write( '.text > p:first-of-type{\n' );
document.write( '    width:100%;margin-top:0;margin-bottom:auto;line-height: 13px;font-size: 12px;\n' );
document.write( '}\n' );
document.write( '.text > p:last-of-type{\n' );
document.write( '    width:100%;text-align:right;color:silver;margin-bottom:-7px;margin-top:auto;\n' );
document.write( '}\n' );
document.write( '.text-l{\n' );
document.write( '    float:left;padding-right:10px;\n' );
document.write( '}        \n' );
document.write( '.text-r{\n' );
document.write( '    float:right;padding-left:10px;\n' );
document.write( '}\n' );
document.write( '.avatar{\n' );
document.write( '    display:flex;\n' );
document.write( '    justify-content:center;\n' );
document.write( '    align-items:center;\n' );
document.write( '    width:25%;\n' );
document.write( '    float:left;\n' );
document.write( '    padding-right:10px;\n' );
document.write( '}\n' );
document.write( '.macro{\n' );
document.write( '    margin-top:5px;width:85%;border-radius:5px;padding:5px;display:flex;\n' );
document.write( '}\n' );
document.write( '.msj-rta{\n' );
document.write( '    float:right;background:white;\n' );
document.write( '}\n' );
document.write( '.msj{\n' );
document.write( '    float:left;background:whitesmoke;\n' );
document.write( '}\n' );
document.write( '.frame{\n' );
document.write( '    background:#e0e0de;\n' );
document.write( '    overflow:auto;\n' );
document.write( '    padding:0;\n' );
document.write( '    position:fixed;\n' );
document.write( '    right:10px;\n' );
document.write( '    bottom:0px;\n' );
document.write( '    width:325px;\n' );
document.write( '}\n' );
document.write( '.panel-heading{\n' );
document.write( '    cursor: pointer;\n' );
document.write( '}\n' );
document.write( '.innerframe{\n' );
document.write( '    height:450px;\n' );
document.write( '}\n' );
document.write( '.innerframe > div:last-of-type{\n' );
document.write( '    position:absolute;bottom:5px;width:100%;display:flex;\n' );
document.write( '}\n' );
document.write( '#messages {\n' );
document.write( '    width:100%;\n' );
document.write( '    list-style-type: none;\n' );
document.write( '    padding:18px;\n' );
document.write( '    position:absolute;\n' );
document.write( '    top:50px;\n' );
document.write( '    bottom:50px;\n' );
document.write( '    display:flex;\n' );
document.write( '    flex-direction: column;\n' );
document.write( '    overflow-y:scroll;\n' );
document.write( '    height: 400px;\n' );
document.write( '\n' );
document.write( '}\n' );
document.write( '.msj:before{\n' );
document.write( '    width: 0;\n' );
document.write( '    height: 0;\n' );
document.write( '    content:\"\";\n' );
document.write( '    top:-5px;\n' );
document.write( '    left:-14px;\n' );
document.write( '    position:relative;\n' );
document.write( '    border-style: solid;\n' );
document.write( '    border-width: 0 13px 13px 0;\n' );
document.write( '    border-color: transparent whitesmoke transparent transparent;            \n' );
document.write( '}\n' );
document.write( '.msj-rta:after{\n' );
document.write( '    width: 0;\n' );
document.write( '    height: 0;\n' );
document.write( '    content:\"\";\n' );
document.write( '    top:-5px;\n' );
document.write( '    left:14px;\n' );
document.write( '    position:relative;\n' );
document.write( '    border-style: solid;\n' );
document.write( '    border-width: 13px 13px 0 0;\n' );
document.write( '    border-color: #ffffff transparent transparent transparent;           \n' );
document.write( '}  \n' );
document.write( 'input:focus{\n' );
document.write( '    outline: none;\n' );
document.write( '}        \n' );
document.write( '::-webkit-input-placeholder { /* Chrome/Opera/Safari */\n' );
document.write( '    color: #d4d4d4;\n' );
document.write( '}\n' );
document.write( '::-moz-placeholder { /* Firefox 19+ */\n' );
document.write( '    color: #d4d4d4;\n' );
document.write( '}\n' );
document.write( ':-ms-input-placeholder { /* IE 10+ */\n' );
document.write( '    color: #d4d4d4;\n' );
document.write( '}\n' );
document.write( ':-moz-placeholder { /* Firefox 18- */\n' );
document.write( '    color: #d4d4d4;\n' );
document.write( '}   \n' );
document.write( '</style>\n' );
document.write( '\n' );
document.write( '</head>\n' );
document.write( '    <body>\n' );
document.write( '        <div class=\"frame\">\n' );
document.write( '          <div class=\"panel panel-primary\" style=\"z-index: 1000\"><div id=\"chat-panel\" class=\"panel-heading\"><b>Chat with us</b></div></div>\n' );
document.write( '          <div class=\"innerframe\">\n' );
document.write( '            <ul id=\"messages\"></ul>\n' );
document.write( '            <div id=\"message-box\">\n' );
document.write( '                <div class=\"msj-rta macro\" style=\"margin:auto\">                        \n' );
document.write( '                    <div class=\"text text-l\" style=\"background:white\">\n' );
document.write( '                        <input class=\"mytext\" placeholder=\"Type a message\"/>\n' );
document.write( '                    </div> \n' );
document.write( '                </div>\n' );
document.write( '            </div>\n' );
document.write( '            </div>\n' );
document.write( '        </div>    \n' );
document.write( '    </body>\n' );
document.write( '    <script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\n' );
document.write( '    <script src=\"app.js\"></script>\n' );
document.write( '    <script type=\"text/javascript\">\n' );
document.write( '        var local = {};\n' );
document.write( 'local.avatar = \"https://image.flaticon.com/icons/png/128/149/149071.png\";\n' );
document.write( '\n' );
document.write( 'var remote = {};\n' );
document.write( 'remote.avatar = \"https://scontent-hkg3-1.xx.fbcdn.net/v/t1.0-9/22308840_218346612033392_2635708369986259675_n.jpg?oh=d8c0a077f912c8b8e79fcf8d1afbf046&oe=5AA43BD8\";\n' );
document.write( '\n' );
document.write( '\n' );
document.write( 'var accessToken = \"ce28c5d1df8a4f9691d8810ecbceaac2\";\n' );
document.write( 'var baseUrl = \"https://api.api.ai/v1/\";\n' );
document.write( '\n' );
document.write( 'function formatTime(date) {\n' );
document.write( '    var hours = date.getHours();\n' );
document.write( '    var minutes = date.getMinutes();\n' );
document.write( '    var ampm = hours >= 12 ? \'PM\' : \'AM\';\n' );
document.write( '    hours = hours % 12;\n' );
document.write( '    hours = hours ? hours : 12; // the hour \'0\' should be \'12\'\n' );
document.write( '    minutes = minutes < 10 ? \'0\'+minutes : minutes;\n' );
document.write( '    var strTime = hours + \':\' + minutes + \' \' + ampm;\n' );
document.write( '    return strTime;\n' );
document.write( '}            \n' );
document.write( '\n' );
document.write( 'function insertChat(who, text){\n' );
document.write( '    var control = \"\";\n' );
document.write( '    var date = formatTime(new Date());\n' );
document.write( '    \n' );
document.write( '     if (who == \"local\"){\n' );
document.write( '        \n' );
document.write( '         control = \'<li style=\"width:100%;\">\' +\n' );
document.write( '                        \'<div class=\"msj-rta macro\">\' +\n' );
document.write( '                            \'<div class=\"text text-r\">\' +\n' );
document.write( '                                \'<p>\'+text+\'</p>\' +\n' );
document.write( '                                \'<p><small>\'+date+\'</small></p>\' +\n' );
document.write( '                            \'</div>\' +\n' );
document.write( '                        \'<div class=\"avatar\" style=\"padding:0px 0px 0px 10px !important\"><img class=\"img-circle\" style=\"width:100%;\" src=\"\'+local.avatar+\'\" /></div>\' +                                \n' );
document.write( '                  \'</li>\';                   \n' );
document.write( '    }else{\n' );
document.write( '        control = \'<li style=\"width:100%\">\' +\n' );
document.write( '                        \'<div class=\"msj macro\">\' +\n' );
document.write( '                        \'<div class=\"avatar\"><img class=\"img-circle\" style=\"width:100%;\" src=\"\'+ remote.avatar +\'\" /></div>\' +\n' );
document.write( '                            \'<div class=\"text text-l\">\' +\n' );
document.write( '                                \'<p>\'+ text +\'</p>\' +\n' );
document.write( '                                \'<p><small>\'+date+\'</small></p>\' +\n' );
document.write( '                            \'</div>\' +\n' );
document.write( '                        \'</div>\' +\n' );
document.write( '                    \'</li>\';   \n' );
document.write( '    }\n' );
document.write( '    $(\"#messages\").append(control);\n' );
document.write( '    var objDiv = document.getElementById(\"messages\");\n' );
document.write( '    objDiv.scrollTop = objDiv.scrollHeight;\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '$(\"#chat-panel\").on(\'click\',function(){\n' );
document.write( '    $(\".innerframe\").toggle();\n' );
document.write( '});\n' );
document.write( '\n' );
document.write( 'function resetChat(){\n' );
document.write( '    $(\"#messages\").empty();\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '$(\".mytext\").on(\"keyup\", function(e){\n' );
document.write( '    if (e.which == 13){\n' );
document.write( '        var text = $(this).val();\n' );
document.write( '        if (text !== \"\"){\n' );
document.write( '            insertChat(\"local\", text);              \n' );
document.write( '            $(this).val(\'\');\n' );
document.write( '            queryBot(text)\n' );
document.write( '        }\n' );
document.write( '    }\n' );
document.write( '});\n' );
document.write( '\n' );
document.write( 'resetChat();\n' );
document.write( '\n' );
document.write( '\n' );
document.write( 'function queryBot(text) {\n' );
document.write( '            $.ajax({\n' );
document.write( '                type: \"POST\",\n' );
document.write( '                url: baseUrl + \"query?v=20150910\",\n' );
document.write( '                contentType: \"application/json; charset=utf-8\",\n' );
document.write( '                dataType: \"json\",\n' );
document.write( '                headers: {\n' );
document.write( '                    \"Authorization\": \"Bearer \" + accessToken\n' );
document.write( '                },\n' );
document.write( '                data: JSON.stringify({ query: text, lang: \"en\", sessionId: \"somerandomthing\" }),\n' );
document.write( '                success: function(data) {\n' );
document.write( '                    insertChat(\"remote\",data.result.fulfillment.speech);\n' );
document.write( '                },\n' );
document.write( '                error: function() {\n' );
document.write( '                    insertChat(\"remote\",\"Internal Server Error\");\n' );
document.write( '                }\n' );
document.write( '            });\n' );
document.write( '    }\n' );
document.write( '\n' );
document.write( '    </script>\n' );
document.write( '</html>\n' );
