document.write( '<!DOCTYPE html>\n' );
document.write( '<html>\n' );
document.write( '<head>\n' );
document.write( '\n' );
document.write( '<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\" crossorigin=\"anonymous\">\n' );
document.write( '<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\n' );
document.write( '\n' );
document.write( '</head>\n' );
document.write( '    <body>\n' );
document.write( '        <div class=\"frame\">\n' );
document.write( '          <div class=\"panel panel-primary\" style=\"z-index: 1000\"><div id=\"chat-panel\" class=\"panel-heading\"><b>Chat with us</b></div></div>\n' );
document.write( '          <div class=\"innerframe\">\n' );
document.write( '            <ul id=\"messages\"></ul>\n' );
document.write( '            <div id=\"message-box\">\n' );
document.write( '                <div class=\"msj-rta macro\" style=\"margin:auto\">                        \n' );
document.write( '                    <div class=\"text text-l\" style=\"background:white\">\n' );
document.write( '                        <input class=\"mytext\" placeholder=\"Type a message\"/>\n' );
document.write( '                    </div> \n' );
document.write( '                </div>\n' );
document.write( '            </div>\n' );
document.write( '            </div>\n' );
document.write( '        </div>    \n' );
document.write( '    </body>\n' );
document.write( '    <script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\n' );
document.write( '    <script src=\"app.js\"></script>\n' );
document.write( '</html>\n' );
